default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: iron_and_motion_app_development
  username: mason
  password: '3689'
  host: localhost
  port: 5432

test:
  <<: *default
  database: iron_and_motion_app_test
  username: mason
  password: '3689'
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: iron_and_motion_app_production
    username: mason
    password: <%= ENV["IRON_AND_MOTION_APP_DATABASE_PASSWORD"] %>
    host: <%= ENV.fetch("IRON_AND_MOTION_APP_DB_HOST", "localhost") %>
    port: <%= ENV.fetch("IRON_AND_MOTION_APP_DB_PORT", 5432) %>

  cache:
    <<: *primary_production
    database: iron_and_motion_app_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: iron_and_motion_app_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: iron_and_motion_app_production_cable
    migrations_paths: db/cable_migrate
